"""added iterator

Revision ID: 53273aa261ea
Revises: bddf7b685c9e
Create Date: 2024-05-05 14:47:27.999227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53273aa261ea'
down_revision: Union[str, None] = 'bddf7b685c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('iterator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'iterator')
    # ### end Alembic commands ###
