"""added iterator for like

Revision ID: 66863b625458
Revises: 53273aa261ea
Create Date: 2024-05-05 15:39:41.858786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66863b625458'
down_revision: Union[str, None] = '53273aa261ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('like_iterator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'like_iterator')
    # ### end Alembic commands ###
