"""add ForeignKey to Filter

Revision ID: 9de3d0c00626
Revises: 
Create Date: 2024-05-06 10:05:06.400786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de3d0c00626'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter', 'uni')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter', sa.Column('uni', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
