"""split tables

Revision ID: bddf7b685c9e
Revises: 6eb892d3c40d
Create Date: 2024-05-04 21:30:13.527176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bddf7b685c9e'
down_revision: Union[str, None] = '6eb892d3c40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=150), nullable=True),
    sa.Column('sex_target', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('age_from', sa.Integer(), nullable=True),
    sa.Column('age_to', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('like',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked_users_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'liked_users')
    op.drop_column('user', 'target')
    op.drop_column('user', 'sex_target')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex_target', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('target', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('liked_users', sa.VARCHAR(), nullable=True))
    op.drop_table('like')
    op.drop_table('filter')
    # ### end Alembic commands ###
