"""update user model

Revision ID: c1e5a30d3044
Revises: 620b12657af6
Create Date: 2024-05-03 19:39:33.838881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e5a30d3044'
down_revision: Union[str, None] = '620b12657af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('craft', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('photo', sa.String(length=150), nullable=False))
    op.add_column('user', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(length=150), nullable=True))
    op.drop_column('user', 'description')
    op.drop_column('user', 'photo')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    op.drop_column('user', 'name')
    op.drop_column('user', 'craft')
    # ### end Alembic commands ###
