"""add target

Revision ID: d3dcb3f5e2ea
Revises: c1e5a30d3044
Create Date: 2024-05-04 09:25:48.617755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dcb3f5e2ea'
down_revision: Union[str, None] = 'c1e5a30d3044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('target', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'target')
    # ### end Alembic commands ###
